[pytest]
testpaths =
    Eventos_Login/tests
    Odakyu_Create_account/tests
    Playwright_demo2_05082026/tests
pythonpath =
    .
    Odakyu_Create_account
    Playwright_demo2_05082026/tests
addopts = -ra
